#  服务配置
server :
  port : 80

# spring配置
spring:
  profiles:
    active: dev
  application:
    name: rls-sys-common-service
  resources:
    cache-period: 10000
 # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rls?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull # JDBC url of the database.
    username: root
    password: zl521131
  jpa:
    database: mysql
    hibernate:
      ddl.auto: create  #创建表方式
    show-sql: true

#  日志配置
logging:
  file: logs/rls-sys--service.log
  level:
    com.rls.sys: debug





