#  服务配置
server :
  port : 80
  context-path: /sys  #项目contextPath
  session-timeout: 60  #ession最大超时时间(分钟)，默认为30
  tomcat:
      max-threads: 100     # tomcat最大线程数，默认为200
  tomcat:
      uri-encoding: UTF-8  # tomcat的URI编码

# spring配置
spring:
  profiles:
    active: dev
  application:
    name: rls-sys-common-service
  data:
    jpa:
      repositories:
        enabled: true
  resources:
    cache-period: 10000
  jpa:
    open-in-view: true
    show-sql: true    #显示执行sql
    generate-ddl: false
    database: mysql
    hibernate:
      ddl-auto: update    #生成表策略
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy  #表/字段的命名映射策略
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect   #数据库方言  mysql 5.7 使用这个
 # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rls?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull # JDBC url of the database.
    username: root
    password: zl521131
    druid:                   #连接池
        initial-size: 5     #初始化  5
        max-active: 20      #最大
        min-idle: 1         #最小
        max-wait: 60000     # 配置获取连接等待超时的时间
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        min-evictable-idle-time-millis: 60000
        max-evictable-idle-time-millis: 300000


#  日志配置
logging:
  file: logs/rls-sys-service.log
  level:
    com.rls.sys: debug





