#  服务配置
server :
  port : 80

# spring配置
spring:
  profiles:
    active: dev
  application:
    name: rls-sys-common-service
  data:
    jpa:
      repositories:
        enabled: true
  resources:
    cache-period: 10000
  jpa:
    open-in-view: true
    show-sql: true    #显示执行sql
    generate-ddl: false
    database: mysql
    hibernate:
      ddl-auto: update    #生成表策略
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy  #表/字段的命名映射策略
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect   #数据库方言  mysql 5.7 使用这个
 # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rls?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull # JDBC url of the database.
    username: root
    password: zl521131


#  日志配置
logging:
  file: logs/rls-sys--service.log
  level:
    com.rls.sys: debug





