# 测试
spring:
    profiles: dev
    application:
    name: rls-sys-service
    datasource:
         driver-class-name: com.mysql.jdbc.Driver
         url: jdbc:mysql://localhost:3306/rls
         username: root
         password: zl521131
    jpa:
        hibernate:
             ddl.auto: create-drop  #其主要作用是：自动创建、更新、验证数据库表结构。create update validate create-drop
        show-sql: true