 #ºËĞÄÅäÖÃÎÄ¼ş
 server:
    port: 80
 spring:
    profiles:
        active: dev
    application:
      name: rls-sys-service
 tomcat:
      uri-encoding: UTF-8
      max-threads: 800
      max-connections: 800
      context-path: /sys
  jackson:
    date-format:  yyyy-MM-dd HH:mm:ss
    time-zone:  UTC